//------------------------------------------------------------------------------
// <auto-generated>
//    Bu kod bir şablondan oluşturuldu.
//
//    Bu dosyada el ile yapılan değişiklikler uygulamanızda beklenmedik davranışa neden olabilir.
//    Kod yeniden oluşturulursa, bu dosyada el ile yapılan değişikliklerin üzerine yazılacak.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OtelRezervasyonWebSitesi.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Odemeler
    {
        public int OdemeID { get; set; }
        public Nullable<int> RezervasyonID { get; set; }
        public Nullable<decimal> Tutar { get; set; }
        public Nullable<System.DateTime> OdemeTarihi { get; set; }
        public string OdemeYontemi { get; set; }
    
        public virtual Rezervasyonlar Rezervasyonlar { get; set; }
    }
}
